# Ignore all directories
**
# Include version directory
!11.2.0.4
# Include database and patch files
!/database/p13390677_112040_Linux-x86-64_1of7.zip
!/database/p13390677_112040_Linux-x86-64_2of7.zip
!/database/patches/p6880880_112000_Linux-x86-64.zip
!/database/patches/p28364007_112040_Linux-x86-64.zip
# Ignore files
Dockerfile*
.docker*
.git*
README.md
!manageOracle.sh
