# Ignore all directories
**
# Include version directory
!11.2.0.2
# Include database and patch files
!/database/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
# Ignore files
Dockerfile*
.docker*
.git*
README.md
!manageOracle.sh
