version: '3'
services:
  PHOENIX:
    image: new199
    container_name: PHOENIX
    volumes:
      - "FS_PHOENIX:/u01/app/oracle/oradata"
      - "FS_SHARE:/share"
    environment:
      CONTAINER_NAME: PHOENIX
      ORACLE_SID: PROD
      DB_UNQNAME: PHOENIX
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: PRIMARY
      ROUTE_PRIORITY: 0
    ports:
      - "10000:1521"

  DALLAS:
    image: new199
    container_name: DALLAS
    volumes:
      - "FS_DALLAS:/u01/app/oracle/oradata"
      - "FS_SHARE:/share"
    environment:
      CONTAINER_NAME: DALLAS
      ORACLE_SID: PROD
      DB_UNQNAME: DALLAS
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: STANDBY
      ROUTE_PRIORITY: 8
    ports:
      - "10001:1521"

  DENVER:
    image: new199
    container_name: DENVER
    volumes:
      - "FS_DENVER:/u01/app/oracle/oradata"
      - "FS_SHARE:/share"
    environment:
      CONTAINER_NAME: DENVER
      ORACLE_SID: PROD
      DB_UNQNAME: DENVER
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: STANDBY
      ROUTE_PRIORITY: 8
    ports:
      - "10002:1521"

  VEGAS:
    image: new199
    container_name: VEGAS
    volumes:
      - "FS_VEGAS:/u01/app/oracle/oradata"
      - "FS_SHARE:/share"
    environment:
      CONTAINER_NAME: VEGAS
      ORACLE_SID: PROD
      DB_UNQNAME: VEGAS
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: FARSYNC
      ROUTE_PRIORITY: 1
    ports:
      - "10003:1521"


volumes:
  FS_SHARE:
  FS_DALLAS:
  FS_DENVER:
  FS_PHOENIX:
  FS_VEGAS:
