version: '3'
services:
  APPPROD:
    image: oraclesean/db:19.11-ee
    container_name: APPPROD
    volumes:
      - FS_APPPROD:/u01/app/oracle/oradata
      - /home/lab/docker/labs/farsync:/docker
    environment:
      CONTAINER_NAME: APPPROD
      ORACLE_SID: APPPROD
      DB_UNQNAME: APPPROD
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: PRIMARY
      DG_TARGET: APPS1DB,APPS2DB
      SETUP_DIR: /docker
      BROKER_SCRIPT: dg_broker.dgs
      BROKER_CHECKS: dg_check.dgs
      SETUP_PRIMARY: dg_setup_primary
      RMAN_DUPLICATE: rman_duplicate
      OPEN_MODE: OPEN

    ports:
      - 10000:1521

  APPS1DB:
    image: oraclesean/db:19.11-ee
    container_name: APPS1DB
    volumes:
      - FS_APPS1DB:/u01/app/oracle/oradata
      - /home/lab/docker/labs/farsync:/docker
    environment:
      CONTAINER_NAME: APPS1DB
      ORACLE_SID: APPPROD
      DB_UNQNAME: APPS1DB
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: STANDBY
      DG_TARGET: APPPROD
      SETUP_DIR: /docker
      BROKER_SCRIPT: dg_broker.dgs
      BROKER_CHECKS: dg_check.dgs
      SETUP_PRIMARY: dg_setup_primary
      RMAN_DUPLICATE: rman_duplicate
      OPEN_MODE: APPLY

    ports:
      - 10001:1521

  APPS2DB:
    image: oraclesean/db:19.11-ee
    container_name: APPS2DB
    volumes:
      - FS_APPS2DB:/u01/app/oracle/oradata
      - /home/lab/docker/labs/farsync:/docker
    environment:
      CONTAINER_NAME: APPS2DB
      ORACLE_SID: APPPROD
      DB_UNQNAME: APPS2DB
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: STANDBY
      DG_TARGET: APPPROD
      SETUP_DIR: /docker
      BROKER_SCRIPT: dg_broker.dgs
      BROKER_CHECKS: dg_check.dgs
      SETUP_PRIMARY: dg_setup_primary
      RMAN_DUPLICATE: rman_duplicate
      OPEN_MODE: APPLY

    ports:
      - 10002:1521

  APPFSDB:
    image: oraclesean/db:19.11-ee
    container_name: APPFSDB
    volumes:
      - FS_APPFSDB:/u01/app/oracle/oradata
      - /home/lab/docker/labs/farsync:/docker
    environment:
      CONTAINER_NAME: APPFSDB
      ORACLE_SID: APPPROD
      DB_UNQNAME: APPFSDB
      ORACLE_PWD: oracle
      PDB_COUNT: 0
      PDB_NAME: 
      ROLE: FARSYNC
      DG_TARGET: 
      SETUP_DIR: /docker
      BROKER_SCRIPT: dg_broker.dgs
      BROKER_CHECKS: dg_check.dgs
      SETUP_PRIMARY: dg_setup_primary
      RMAN_DUPLICATE: rman_duplicate
      OPEN_MODE: MOUNT

    ports:
      - 10003:1521

volumes:
  FS_APPPROD:
  FS_APPS1DB:
  FS_APPS2DB:
  FS_APPFSDB:
